CREATE TABLE TBL_STUDENTS(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT,
CLASS INT);

INSERT INTO TBL_STUDENTS VALUES
(1,'AARAV',17,8),
(2,'VIKRAM',16,4),
(3,'PRIYA',15,6),
(4,'ROHAN',16,7),
(5,'SITA',17,8),
(6,'KIRAN',15,6);

SELECT * FROM TBL_STUDENTS

BEGIN TRANSACTION
	UPDATE TBL_STUDENTS
	SET NAME = 'AMAN'
	WHERE ID=1;
	
	COMMIT TRANSACTION


DROP TABLE TBL_STUDENTS
BEGIN TRANSACTION
	INSERT INTO TBL_STUDENTS VALUES
	(7,'ABHISHEK',13,6),
	(8,'SARTHAK',"17",9),
	(9,'PARTH',15,6);

	COMMIT TRANSACTION


BEGIN TRY
	BEGIN TRANSACTION
    INSERT INTO TBL_STUDENTS(ID, NAME, AGE, CLASS)VALUES
	(7,'ROHIT',16,7),
	(8,'SHYAM','seven',8),
	(9,'KARAN',15,6);
	COMMIT TRANSACTION
	PRINT 'TRANSACTION SUCCESSFUL'
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION
	PRINT 'TRANSACTION ABORTED'
END CATCH


------SAVEPOINTS------
BEGIN TRY
	BEGIN TRANSACTION
    INSERT INTO TBL_STUDENTS(ID, NAME, AGE, CLASS)VALUES
	(7,'ROHIT',16,7);
	SAVE TRANSACTION SAVE_01
	--COMMIT NECESSARY--
	BEGIN TRANSACTION 
	INSERT INTO TBL_STUDENTS(ID, NAME, AGE, CLASS)VALUES
	(8,'SHYAM','seven',8);
	SAVE TRANSACTION SAVE_02
	PRINT 'TRANSACTION SUCCESSFUL'
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION SAVE_01
END CATCH